{{
   const btoa = require('btoa');
   const btoastring = 'werner.weber@gmail.com:Password123!';
   const client_id = 'reactory';
   const client_secret = 'bYGgEjp9U9BBi3R3RPx8DAjm+8thTKdpymngp2kU+50=';
   exports.authToken = btoa(btoastring);
   $global.client_id = client_id;
   $global.client_secret = client_secret;
}}
POST http://localhost:4000/login HTTP/1.1
Content-Type: application/json
Accept: application/json
x-client-key: {{$global.client_id}}
x-client-pwd: {{$global.client_secret}}
Authorization: Basic {{authToken}}

{{
  // post request script
  const assert = require('assert');
  const result = response.parsedBody;
  const token = result.user.token;
  console.log(token);
  
  assert.equal(response.statusCode, 200, 'Expected 200 OK response');
  assert.notEqual(token, null, 'Expected token to be returned');

  $global.token = token;
}}

HTTP/1.1 200  - OK
x-powered-by: Express
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: X-Client-Key,X-Client-Pwd,x-client-key,x-client-pwd,x-client-version,x-client-name
content-language: en-US
content-type: application/json; charset=utf-8
content-length: 466
etag: W/"1d2-RfLG+Zk0exwhrwFinGKZ420es6I"
date: Thu, 27 Mar 2025 13:30:04 GMT
connection: close
###
GET http://localhost:4000/reactor-mcp/sse
Authorization: Bearer {{$global.token}}
x-client-key: {{$global.client_id}}
x-client-pwd: {{$global.client_secret}}
Accept: text/event-stream

{{
  // get request script
  const assert = require('assert');
  const result = response.parsedBody;
  console.log(result);
  
  assert.equal(response.statusCode, 200, 'Expected 200 OK response');
  assert.notEqual(result, null, 'Expected result to be returned');
}}
###
SSE http://localhost:4000/reactor-mcp/messages?sessionId=
Authorization: Bearer {{$global.token}}
x-client-key: {{$global.client_id}}
x-client-pwd: {{$global.client_secret}}
Event: message

{{@streaming
  async function writeStream(){
    await sleep(10000);
  }
  exports.waitPromise = writeStream();
}}