# Mutation and union types for system graph

type CatalogNodeSyncSuccess {
  node: ReactorNode!
  message: String
}

type CatalogNodeSyncFailure {
  node: ReactorNode!
  errors: [String!]
}

union CatalogNodeSyncResult = CatalogNodeSyncSuccess | CatalogNodeSyncFailure

type ReactorNodeCatalogIndexSuccess {
  nodes: [ReactorNode!]
  message: String
}

type ReactorNodeCatalogIndexFailure {
  errors: [String!]
}

union ReactorNodeCatalogIndexResult = ReactorNodeCatalogIndexSuccess | ReactorNodeCatalogIndexFailure

type ReactorCreateNodeLinkSuccess {
  link: ReactorNodeLink!
  message: String
}

type ReactorCreateNodeLinkFailure {
  link: ReactorNodeLink!
  error: String
}

union ReactorNodeLinkCreateResult = ReactorCreateNodeLinkSuccess | ReactorCreateNodeLinkFailure

type ReactorNodeLinkUpdateSuccess {
  link: ReactorNodeLink!
  message: String
}

type ReactorNodeLinkUpdateFailure {
  link: ReactorNodeLink!
  error: String
}

union ReactorNodeLinkUpdateResult = ReactorNodeLinkUpdateSuccess | ReactorNodeLinkUpdateFailure

type ReactorDeleteNodeLinkSuccess {
  id: Int!
  message: String
}

type ReactorDeleteNodeLinkFailure {
  id: Int!
  error: String
}

union ReactorNodeLinkDeleteResult = ReactorDeleteNodeLinkSuccess | ReactorDeleteNodeLinkFailure

type ReactorSysteGraphSaveFailure {
  id: Int!
  error: String
}

type ReactorSystemGraphSaveSuccess {
  success: Boolean
  message: String
}

union ReacorSystemGraphSaveResult = ReactorSysteGraphSaveFailure | ReactorSystemGraphSaveSuccess

type ReactorProjectDocumentationUpdateSuccess {
  project: ReactorProject!
  message: String
}

type ReactorProjectDocumentationUpdateFailure {
  error: String
}

type ReactorProjectUpdateSuccess {
  id: String!
  project: ReactorProject!
  message: String
}

type ReactorProjectUpdateFailure {
  error: String
  id: String!
}

union ReactorProjectUpdateResult = ReactorProjectUpdateSuccess | ReactorProjectUpdateFailure


union ReactorProjectDocumentationUpdateResult = ReactorProjectDocumentationUpdateSuccess | ReactorProjectDocumentationUpdateFailure

type Mutation {
  ReactorCreateNodeLink(input: ReactoryNodeLinkInput!): ReactorNodeLinkCreateResult!
  ReactorUpdateNodeLink(input: ReactoryNodeLinkInput!): ReactorNodeLinkUpdateResult!
  ReactorDeleteNodeLink(id: Int!): ReactorNodeLinkDeleteResult!
  ReactorSyncCatalogNodes(request: CatalogCrawlRequest!): [CatalogNodeSyncResult!]!
  ReactorIndexNodes(filter: ReactorProjectFilter!): ReactorPagedNodes!
  ReactorSaveSystemGraph(graph: ReactorSystemGraphInput!): ReacorSystemGraphSaveResult!
  ReactorUpdateProjectDocumentation(projectId: String!, additionalDocumentation: [ReactorProjectDocumentationInput!]!): ReactorProjectDocumentationUpdateResult!
  ReactorUpdateProject(projectId: String!, updates: ReactorProjectInput!): ReactorProjectUpdateResult!
}