import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  Index,
  CreateDateColumn,
  UpdateDateColumn,
} from 'typeorm';

/**
 * A single entry in a conversation's message log.
 *
 * Conversation *sessions* stay in MongoDB (`reactor_conversations`); the
 * append-heavy message log lives here so a long conversation cannot push the
 * session document toward the 16 MB BSON ceiling, and so windowed reads,
 * archive/compaction and search become indexed SQL rather than array rewrites.
 *
 * `mongo_id` preserves the `_id` the message carried while it lived in the
 * Mongo `history` array. That id is the paging cursor the client round-trips
 * (`historyWindow.oldestId` -> `before`), so keeping it stable is what lets the
 * read contract survive the cutover unchanged.
 */
/**
 * NOTE ON INDEXES
 *
 * Every index this table relies on is declared here, not only in the migration.
 * The runtime DataSource runs with `synchronize: true` outside production, and
 * TypeORM reconciles the schema against entity metadata - which means it DROPS
 * any index it cannot see declared. Indexes created only by migration SQL
 * therefore disappear on the next server start. That is exactly what happened to
 * the unique `(conversation_id, seq)` guard, and its absence let concurrent
 * appends collide on `MAX(seq)+1` and write duplicate `seq` values.
 *
 * The one exception is the `pg_trgm` GIN index on `search_text`, which TypeORM
 * cannot express and which is therefore migration-only (production runs with
 * `synchronize: false`, so it survives there).
 */
@Index('IDX_rcm_conv_archived_seq', ['conversationId', 'archived', 'seq'])
@Index('IDX_rcm_conv_role_seq', ['conversationId', 'role', 'seq'])
@Index('IDX_rcm_conv_seq', ['conversationId', 'seq'], { unique: true })
@Entity({ name: 'reactor_conversation_messages' })
export default class ReactorConversationMessage {
  /** Internal row identity. Not exposed to clients; `mongoId` is. */
  @PrimaryGeneratedColumn({ type: 'bigint' })
  id: string;

  /**
   * The Mongo subdocument `_id` this row originated from, or a freshly minted
   * 24-hex id for messages created after the cutover. Unique so backfill is
   * idempotent.
   */
  @Index('IDX_rcm_mongo_id', { unique: true, where: '"mongo_id" IS NOT NULL' })
  @Column({ name: 'mongo_id', type: 'char', length: 24, nullable: true })
  mongoId?: string | null;

  /** Mongo `_id` of the owning conversation session. */
  @Column({ name: 'conversation_id', type: 'char', length: 24 })
  conversationId: string;

  /**
   * Monotonic position within the conversation, assigned as `MAX(seq)+1`.
   * This is the only ordering source for a transcript; `messageTs` is purely
   * informational because wall clocks can skew between writers.
   */
  @Column({ name: 'seq', type: 'bigint' })
  seq: string;

  /** `system` | `user` | `assistant` | `tool`. */
  @Column({ name: 'role', type: 'varchar', length: 32 })
  role: string;

  /**
   * Message body. Stored as JSONB because a message may carry a plain string or
   * a provider content-part array. The service unwraps JSON strings on read.
   */
  @Column({ name: 'content', type: 'jsonb', nullable: true })
  content?: unknown;

  /** Flattened reasoning/thinking text. */
  @Column({ name: 'thinking', type: 'text', nullable: true })
  thinking?: string | null;

  /** Provider-native reasoning blocks, replayed verbatim where required. */
  @Column({ name: 'thinking_blocks', type: 'jsonb', nullable: true })
  thinkingBlocks?: unknown;

  /** Images generated by image-capable models. */
  @Column({ name: 'images', type: 'jsonb', nullable: true })
  images?: unknown;

  @Column({ name: 'refusal', type: 'text', nullable: true })
  refusal?: string | null;

  @Column({ name: 'tool_call_id', type: 'varchar', length: 255, nullable: true })
  toolCallId?: string | null;

  @Column({ name: 'tool_name', type: 'varchar', length: 255, nullable: true })
  toolName?: string | null;

  @Column({ name: 'tool_args', type: 'jsonb', nullable: true })
  toolArgs?: unknown;

  @Column({ name: 'tool_calls', type: 'jsonb', nullable: true })
  toolCalls?: unknown;

  @Column({ name: 'tool_results', type: 'jsonb', nullable: true })
  toolResults?: unknown;

  @Column({ name: 'tool_errors', type: 'jsonb', nullable: true })
  toolErrors?: unknown;

  /**
   * The full provider response envelope for the turn. Retained rather than
   * trimmed because token/cost analytics read `usage` from it.
   */
  @Column({ name: 'provider_response', type: 'jsonb', nullable: true })
  providerResponse?: unknown;

  @Column({ name: 'component', type: 'varchar', length: 255, nullable: true })
  component?: string | null;

  @Column({ name: 'rating', type: 'integer', nullable: true })
  rating?: number | null;

  @Column({ name: 'annotations', type: 'jsonb', nullable: true })
  annotations?: unknown;

  @Column({ name: 'audio', type: 'jsonb', nullable: true })
  audio?: unknown;

  /**
   * Flattened, searchable text derived from content (and thinking). Maintained
   * on write so session-list search is an indexed predicate rather than a
   * regex scan.
   */
  @Column({ name: 'search_text', type: 'text', nullable: true })
  searchText?: string | null;

  /**
   * True once the message has been displaced from the active context by
   * truncation or compaction. Archived rows are retained and remain visible to
   * the UI on request, so this is a client-visible attribute, not bookkeeping.
   */
  @Column({ name: 'archived', type: 'boolean', default: false })
  archived: boolean;

  @Column({ name: 'archived_at', type: 'timestamp with time zone', nullable: true })
  archivedAt?: Date | null;

  /** `truncated` | `compacted` | `cleared`. */
  @Column({ name: 'archived_reason', type: 'varchar', length: 64, nullable: true })
  archivedReason?: string | null;

  /** Original message timestamp. Informational only; never used for ordering. */
  @Column({ name: 'message_ts', type: 'timestamp with time zone', nullable: true })
  messageTs?: Date | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamp with time zone' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamp with time zone' })
  updatedAt: Date;
}
